project: 
  type: website

website:
  title: "Daniel Dominguez Portfolio"
  favicon: Images/logo.png
  back-to-top-navigation: true
  repo-url: https://github.com/your_url
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Daniel Dominguez"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/dann-dominguez/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "Senior Project"
        file: projects.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Data Cleansing"
        file: cleansing.qmd
      - text: "Data Exploration"
        file: exploration.qmd
      - text: "Story Telling"
        file: story_telling.qmd
      - text: "Machine Learning"
        file: ml.qmd
      - text: "Full Stack"
        file: full_stack.qmd
      - text: "Competition"
        file: competition.qmd
      
  sidebar:
    - title: "Senior Project"
      style: "docked"
      background: light
      contents:
        - text: "Senior Project"
          file: projects.qmd
        - text: "---"
        - text: "Data Engineering for DS"
          file: Projects/project1.qmd
        - text: "---"
        - text: "SQL Project"
          file: Projects/project2.qmd
        - text: "---"
        - text: "Data Maturity"
          file: Projects/project3.qmd
        - text: "---"

        #continue the pattern if you need more links
        #copy paste from title and keep it indented to sidebar to add additonal sidebar navigation for other pages

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



