---
layout: cv
title: Daniel Dominguez
---

385.328.1955
| <a href="danndch7@gmail.com">danndch@gmail.com</a>
| <a href="https://www.linkedin.com/in/dann-dominguez"/> LinkedIn</a>
| <a href="https://www.byui.edu/mathematics/student-resources/data-science">Data Science Program</a>

***

## Education.
#### B.Sc. Data Science                                                                    
*__Brigham Young University Idaho (Rexburg, ID)__*

Jan 2020 - April 2024

* Minor: Statistics, Business Analytics\
* Certificates: Machine Learning, Database, Applied Programming.

## Skills

|Data Analysis, Wrangling, and Visualization:|Programming:|Database Design and Administration:|
|---|---|---|
| •	Pyspark and SQL (Big Data)  | •	Python  | •	SQL  |
| •	R, Python  | •	Pytorch, TensorFlow   | • PosrgreSQL  |
| •	Statistical Analysis in R  |  •	C# | • Relational and Non Relational DB  |
| •	Tableau, Domo, Power BI  |   |   |

: Skills {tbl-colwidths="[27,25]"}


## Work Experience.
### Data Analyst.

*__BYUI Communications (Rexburg, ID)__*

Oct 2021- Present

* Designed and implemented a GA4-based analytics funnel to analyze the University Admissions process, understanding the story and identifying key stages where applicants face delays or drop out. Utilized insights to propose strategic improvements, significantly enhancing process efficiency and applicant experience. \
* Established pipeline from Twilio API in Python, retrieving 30K+ messages per month, ETL the data to connect to a dashboard on Power BI with the purpose of recognizing messaging trends, dropout, sentiment analysis, usage by 33 university departments, and billing.\
* Leveraged web-scraping in R data of 94K pages, to optimize user experiences and drive success, identifying errors and updating SEO content to improve accessibility and usability.\
* Proficiency in Google Analytics and GA4, to monitor and evaluate engagement data for 60,000+ students, 200,000+ alumni, and various stakeholders, translating insights into meaningful visual reports in Looker Studio, for 33 different University departments.

### Data Science Tutor.
*__BYUI Math Department (Rexburg, ID)__*

Sep 2023 - Present

* Aid students with their questions to meet rubrics on assignments from different courses such as: Data Science Programing, Data Wrangling, Big Data, Machine Learning.



## Projects.

### iWorq Consulting Project  (Remote).
*__Apr-Jul 2023__*\

* Automated a live dashboard to seamlessly retrieve data from AWS-S3, working of over 9 million CSV data points into the refined Parquet format using R. This transformative process empowered intricate feature engineering, culminating in early predictions of service cancellations based on client usage patterns.\

### What’s That Fish.
*__Apr-Jul 2023__* \

* Developed a fish identification app utilizing Convolutional Neural Networks (92% accuracy) to recognize trout species from photos. Deployed the app on Google Firebase, enabling seamless photo storage and database integration for user interactions.\ 


### Sinclair Tire Dealership.
*__(BYUI Data Science Society)  Apr-Jul 2023__*\

* Developed on Streamlit an analytics tool to Web-scrape a given URL to aid a tire dealership from a given URL and retrieve information to help establish retail price according to the competition. \

### John Deer - Stotz.
*__(BYUI Data Science Society)  Jan-Apr 2023__*\

* Project manage to establish a data pipeline and do ETL Process working with the John Deere API to feed a dashboard. The scope of the project was to do exploratory analysis to understand the data for future projects.\

### Beehive Credit Union.
*__(BYUI Data Science Society)  Sep-Dec 2022__*\

* Employed Python, Spark, and TensorFlow to create a machine learning model, enabling Beehive Credit Union to make informed decisions about new possible store locations by analyzing National Census Data and institutional data.

## Volunteer

### Data Science Society Leadership Apr 2023-Present
*__BYU-I Data Science Society	Rexburg, ID__* \

* Led and structured the efforts of 11 projects, maintaining regular contact and meetings with the 22 project managers to facilitate project progress, tools, and deliver the final products by the due date. \
